### ISSUE TITLE
Could I send a message use exchange sever?

### ISSUE THREAD

**Issue by 18911246236a** [jetseven/skpsmtpmessage#16]
I used exchange sever to send email but it always failed to connect the sever, I set the parameters as follows
    SKPSMTPMessage *message = [[SKPSMTPMessage alloc] init];
    message.fromEmail = account.email;
    message.toEmail = @"my@test.com";
    message.requiresAuth = YES;
    message.wantsSecure = YES;
    message.subject = @"test";
    message.delegate = self;
    message.relayHost = @"exchange.com";
    message.login = account.username;
    message.pass = account.password;

**Comment by jetseven** [comment]
Sorry for the late response. I would check the ports Exchange works on and make sure the library is using it. It tries a couple of defaults, but if Exchange doesn't work on 25 or 465, you'll need to add the right one.
