### ISSUE TITLE
Unzip issue

### ISSUE THREAD

**Issue by matrosovDev** [jetseven/skpsmtpmessage#17]
Hi nice library. I have a question. When I attach zip form gmail using web site and send it to Rackspace everything works good.

But when I attached data using you library, then I can unzip file

I also created question here:

http://stackoverflow.com/questions/25663638/rackspce-compressed-zipped-folders-error

SKPSMTPMessage *test_smtp_message = [[SKPSMTPMessage alloc] init];

```
test_smtp_message.email_id = email.email_id;

test_smtp_message.delegate = self;
test_smtp_message.fromEmail = @"email here";
test_smtp_message.toEmail = @"email here"; 
test_smtp_message.relayHost = @"";
test_smtp_message.requiresAuth = YES;
test_smtp_message.login = @"login here";
test_smtp_message.pass = @"password here";
test_smtp_message.wantsSecure = YES; // smtp.gmail.com doesn't work without TLS!
test_smtp_message.subject = @"TEST";
// test_smtp_message.validateSSLChain = NO; // Only do this for self-signed certs!

NSMutableArray *parts_to_send = [NSMutableArray array];

NSString *plainText = [self plainText:email];

NSDictionary *plainPart = [NSDictionary dictionaryWithObjectsAndKeys:@"text/plain",
                           kSKPSMTPPartContentTypeKey,
                           plainText,
                           kSKPSMTPPartMessageKey,
                           @"8bit",
                           kSKPSMTPPartContentTransferEncodingKey,
                           nil];

[parts_to_send addObject:plainPart];

NSString *zipName = [NSString stringWithFormat:@"%@.zip", email.email_id];

NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
NSString *documentsDirectory = [paths objectAtIndex:0];
NSString *filePath = [documentsDirectory stringByAppendingPathComponent:zipName];

filePath = @"/Users/Alex/Library/Application Support/iPhone Simulator/7.1/Applications/D5D29C45-F2C0-4352-9102-FA59CA6B6E83/Documents/archivename.zip";

NSData *image_data = [NSData dataWithContentsOfFile:filePath];

NSDictionary *vcfPart = [NSDictionary dictionaryWithObjectsAndKeys:@"text/directory;\r\n\tx-unix-mode=0644;\r\n\tname=\"doc.zip\"",kSKPSMTPPartContentTypeKey,
                         @"attachment;\r\n\tfilename=\"doc.zip\"",kSKPSMTPPartContentDispositionKey,[image_data encodeBase64ForData],kSKPSMTPPartMessageKey,@"base64",kSKPSMTPPartContentTransferEncodingKey,nil];

[parts_to_send addObject:vcfPart];



test_smtp_message.parts = parts_to_send;

// Set core data object SAPEmail to state composing

//HighestState = 0;

[test_smtp_message send];

NSDictionary *params = @{kEmail_id: email.email_id,
                         kStatus: @(EmailStatusInProgress)};

[SAPCoreDataEmailHelper setEmailWithParams:params withSuccess:nil];
```

**Comment by jetseven** [comment]
I don't work with this enough anymore to know exactly what's going on. It sounds like Rackspace doesn't like the MIME encoding the library is doing for multipart messages. I would compare the raw output of an email from this library compared to the raw output of the email from a client that works with Rackspace. Look at the MIME headers and see what's different.

**Comment by matrosovDev** [comment]
Ok thank you, but for example if it will be different how can I repair it. Because Rackspace forward email to the gmail and it works on gmail perfect.

I supposed that I should modify with this:

NSDictionary *vcfPart = [NSDictionary dictionaryWithObjectsAndKeys:@"application/zip;\r\n\tx-unix-mode=0644;\r\n\tname=\"doc.zip\"",kSKPSMTPPartContentTypeKey,
                             @"attachment;\r\n\tfilename=\"doc.zip\"",kSKPSMTPPartContentDispositionKey,[zipData encodeBase64ForData],kSKPSMTPPartMessageKey,@"base64",kSKPSMTPPartContentTransferEncodingKey, nil];

Thank you for help and library

**Comment by matrosovDev** [comment]
how can I get this raw data? I am not expert in mail. I thought I need two zip files, but I can't open it in txt. Do I need to have whole email?

**Comment by jetseven** [comment]
It depends on your mail client. In Apple Mail, I choose View -> Message -> Raw Source

Below is an example of what I would look for. It shows the MIME headers for both the text and the zip data. These were sent from Apple Mail. 

```
--Apple-Mail=_B5E48CD5-247C-4E93-A44D-ECFE55E9DCAA
Content-Transfer-Encoding: 7BIT
Content-Type: TEXT/PLAIN;
    charset=us-ascii

Some text

--Apple-Mail=_B5E48CD5-247C-4E93-A44D-ECFE55E9DCAA
Content-Disposition: ATTACHMENT;
    filename="Screen Shot 2014-07-10 at 12.07.51 PM.zip"
Content-Type: APPLICATION/ZIP;
    name="Screen Shot 2014-07-10 at 12.07.51 PM.zip";
    x-unix-mode=0644
Content-Transfer-Encoding: BASE64

<Blob of Base64>
```

Here's what I see sending the test message from the library (I don't have a project to easily send a zip file):

```
--SKPSMTPMessage--Separator--Delimiter
Content-Disposition: attachment;
    filename="test.vcf"
Content-Type: text/directory;
    x-unix-mode=0644;
    name="test.vcf"
Content-Transfer-Encoding: base64
```

Off the bat I can see Apple Mail uses all caps for the MIME values APPLICATION/ZIP and BASE64. It may be as simple as changing the library to use all caps. You can see the library is writing the MIME headers in lines 880-891 of SKSMTPMessage.m.  You may see additional differences when you compare a ZIP file.

**Comment by matrosovDev** [comment]
Works! =) But still want work with WebMail client.

Hi, thank you that you help me, really helpful comments I just used your demo projects, and add a little changes to image attachment replace it to zip in code.

NSData *zipData = [NSData dataWithContentsOfFile:filePath];
            NSDictionary *zip_part = [NSDictionary dictionaryWithObjectsAndKeys:
                                        @"inline;\r\n\tfilename=\"doc.zip\"",kSKPSMTPPartContentDispositionKey,
                                        @"base64",kSKPSMTPPartContentTransferEncodingKey,
                                        @"application/zip;\r\n\tname=doc.zip;\r\n\tx-unix-mode=0666",kSKPSMTPPartContentTypeKey,
                                        [zipData encodeWrappedBase64ForData],kSKPSMTPPartMessageKey,
                                        nil];

```
        [parts_to_send addObject:zip_part];
```

I tested it with gmail and rackspace account using Mac Mail client. It works perfect. There is no problem right now. Seems in the code I described at first I miss something:

NSDictionary *vcfPart = [NSDictionary dictionaryWithObjectsAndKeys:@"text/directory;\r\n\tx-unix-mode=0644;\r\n\tname=\"doc.zip\"",kSKPSMTPPartContentTypeKey,
                         @"attachment;\r\n\tfilename=\"doc.zip\"",kSKPSMTPPartContentDispositionKey,[image_data encodeBase64ForData],kSKPSMTPPartMessageKey,@"base64",kSKPSMTPPartContentTransferEncodingKey,nil];

Seems everything is ok with RAW data. I tried to send email via gmail front-end and compare it with raw data from application. Booth seems looks ok

**Comment by jetseven** [comment]
Do you have changes that should be rolled back into the project, or should I just close this?

**Comment by matrosovDev** [comment]
No sorry I think we can close it, it was my mistake. When I work with you code, I seems delete few \n and inlines that's why the email has a problem.
