### ISSUE TITLE
Library doesn't appear to work when executed as background task

### ISSUE THREAD

**Issue by jgallen23** [jetseven/skpsmtpmessage#3]
original issue here: http://code.google.com/p/skpsmtpmessage/issues/detail?id=57

**Comment by jetseven** [comment]
Looks like there's a problem scheduling on the the Run Loop from a background queue. This fails:

```
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [testMsg send]; //testMsg is an SKPSMTPMessage object
    });
```

The main queue has a run loop managed by the system, so this works:

```
    dispatch_async(dispatch_get_main_queue(), ^{
        [testMsg send]; //testMsg is an SKPSMTPMessage object
    });
```

I'll investigate the right way to use NSRunLoop from a background queue.

**Comment by jetseven** [comment]
I just pushed changes to a new branch that address this by explicitly scheduling timers and streams on the main thread and run loop. The demo app uses dispatch_async and it works there.

**Comment by jgallen23** [comment]
Awesome, I'll check it out

**Comment by josea** [comment]
It seems that these changes were never merged back to the Master branch. We are currently having the same issue (wouldn't make sense to create a pull request for this fix). Please advise. Thank you.

**Comment by jetseven** [comment]
I just merged this back into the master. The fixes seem to work, but the runloop is an imperfect fit with GCD (and consequently NSOperation) style asynchrony. The issues were complex enough that I created a [new project](https://github.com/jetseven/JSMailSender) for SMTP based on advice from Apple DTS.

**Comment by josea** [comment]
Thanks.
