### ISSUE TITLE
when mail subject is Chinese,then tittle will turn out some unreadable code

### ISSUE THREAD

**Issue by allanpk716** [jetseven/skpsmtpmessage#5]
And change this will be ok.

in SKPSMTPMessage.m 

you can search it

//    NSData *messageData = [message dataUsingEncoding:NSASCIIStringEncoding allowLossyConversion:YES];
    NSData *messageData = [message dataUsingEncoding:NSUTF8StringEncoding allowLossyConversion:YES];

**Comment by jetseven** [comment]
Just added this to the devel branch. Thanks!
